[alembic]
# path to migration scripts
script_location = alembic

# template used to generate migration files
# file_template = %%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present.
# defaults to the current working directory.
prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# as well as the timestamp of the revision.
# If specified as a string, it will be passed to dateutil.tz.gettz().
# leave blank to use the system timezone.
# timezone =

# max length of characters to apply to the
# "caveat" field when rendering the revision message.
# max_caveat_length = 50

# the string output with "revision -r" when revving
# down to a base revision.  If left at the default
# of '-1', will output '-> base_rev'.
# down_rev_placeholder = -1

# SQLAlchemy database URL.
# If not specified here, the URL will be pulled from
# the environment variable DATABASE_URL.
sqlalchemy.driver = postgres
sqlalchemy.url = postgresql://user:password@localhost/dbname

# logging configuration
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s